fix = true
# unsafe-fixes = true

[lint]
select = [
    "B",     # flake8-bugbear
    "C4",    # flake8-comprehensions
    "F",     # Pyflakes
    "I",     # isort
    "ISC",   # flake8-implicit-str-concat
   "RUF100", # unused noqa (yesqa)
    "UP",    # pyupgrade
]
